version: '3'
services:
  # Service pour Keycloak
  keycloak:
    image: keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command: ["start-dev"]
    networks:
      - my-network

  # Service pour PostgreSQL (nécessaire pour SonarQube)
  postgres:
    image: postgres:13
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    networks:
      - sonar-network

  # Service pour SonarQube
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - sonar-network

  # Service pour Angular
  angular-app:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:80"
    depends_on:
      - keycloak
    networks:
      - my-network

# Configuration des réseaux
networks:
  my-network:
    driver: bridge
  sonar-network:
    driver: bridge
