services:
  # Service pour Keycloak
  keycloak:
    image: keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command: ["start-dev"]
    networks:
      - my-network

  # Service pour Angular
  angular-app:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:80"
    depends_on:
      - keycloak
    networks:
      - my-network

# Configuration du réseau
networks:
  my-network:
    driver: bridge