version: '3.8'

services:
  # Service pour Keycloak
  keycloak:
    image: keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command: ["start-dev"]
    networks:
      - groupeisi-network

  # Service pour l'application Angular (environnement de dev)
  angular-app:
    image: julesbet176/groupeisi-frontend:latest
    container_name: angular-app-dev
    ports:
      - "4200:80"
    depends_on:
      - keycloak
    networks:
      - groupeisi-network

  # Prometheus pour la collecte des métriques
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - groupeisi-network

  # Grafana pour la visualisation des métriques
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - groupeisi-network

networks:
  groupeisi-network:
    driver: bridge