apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-etablissement-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-etablissement-frontend
  template:
    metadata:
      labels:
        app: gestion-etablissement-frontend
    spec:
      containers:
      - name: gestion-etablissement-frontend
        image: julesbest176/gestion-etablissement-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "200Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5