apiVersion: v1
kind: Service
metadata:
  name: gestion-etablissement-frontend
  namespace: groupeisi
spec:
  selector:
    app: gestion-etablissement-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP