FROM ubuntu:20.04

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    lsb-release \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Installer Minikube (version spécifique pour éviter les problèmes futurs)
ENV MINIKUBE_VERSION=v1.30.1
RUN curl -Lo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64 \
    && chmod +x /usr/local/bin/minikube

# Utiliser le driver Docker pour éviter VirtualBox
ENV MINIKUBE_HOME=/root
ENV KUBECONFIG=/root/.kube/config

# Exposer les ports nécessaires
EXPOSE 8443 2379 2380 10250 10251 10252 30000-32767

# Définir le point d'entrée
ENTRYPOINT ["minikube"]
